### PR TITLE
warn when options for matchers aren't a Hash - Issue #1395

### PR DESCRIPTION
**Pull request by twalpole**

### CODE REVIEW

**Comment by abotalov** [comment]
Do you think it makes sense to also output a warning for Finders and Actions?

**Comment by twalpole** [comment]
While I want to say "yes it makes sense" we quickly run into issues where lots of warnings are produced for one call -- ie  the actions call finders and each will then issue its own warning, and I think that would start to get confusing.   I guess we could just blank out the options if the object passed in isn't a Hash - which would mean only the initial method receiving the non hash object would warn.  thoughts?

**Comment by abotalov** [comment]
If I would do it I would probably parse `args` in Query#initialize.

If `args` are wrong, it's probably possible to invoke `caller` and find the last element of an array that contains a substring `/capybara/` or something like it. Then to get a method name we can invoke e.g.
```ruby
line[/in `(.+)'/, 1]
```

**Comment by twalpole** [comment]
I'm not 100% sure that would always give us the method the user is calling though which would create confusing warnings.  I'll have to think about it a bit

**Comment by twalpole** [comment]
Thinking about this,  I don't think it would work for chained finds or things like page.find(...), page.has_css?(....)  etc -- I guess we could filter out certain files (session.rb, etc)  but I think it would start to get messy.

**Comment by abotalov** [comment]
It looks like chained methods don't get into trace:
```ruby
class A
  def a
    puts caller
  end

  def b
    self
  end
end
A.new.b.a # `b` method doesn't appear here
```

The only concern I have is a folder `capybara` that might appear in user's / some library's code. To mitigate it we can search for `/lib/capybara/node/finders.rb` and hope that some other library (or a user) won't have it...

So inspecting `caller` feels like a hack :(

**Comment by twalpole** [comment]
hmmm -- interesting -- when I tried it with page.has_link?  the last "capybara" entry in caller was 
"/Users/twalpole/Projects/jnicklas-capybara/lib/capybara/session.rb:686:in `block (2 levels) in <class:Session>'",    -  which I assume came from the page method

**Comment by twalpole** [comment]
@abotalov -  as you can see from the PR - I've implemented something for actions too, but finders gets more complicated due to the variable args functions -- maybe a hack using caller is a cleaner solution.  I'm going to think about it for a bit

**Pull request closed without merging**
