### PR TITLE
warn when attempting to select a disabled option - Issue #1531

### PR DESCRIPTION
**Pull request by twalpole**

### CODE REVIEW

**Comment by Vanuan** [comment]
The use case is this:
I have a cucumber test that is working fine. Than I add a "disabled" option to some items dynamically. The test still passes, while a user couldn't select an option.

**Comment by twalpole** [comment]
@Vanuan What driver are you using?

**Comment by Vanuan** [comment]
It's phantomjs

**Comment by Vanuan** [comment]
Posted there https://github.com/ariya/phantomjs/issues/13303

**Comment by Vanuan** [comment]
Oh, no it's poltergeist

**Comment by twalpole** [comment]
@Vanuan but is it actually selecting the option, or just ignoring the select --- I would hope it's just ignoring the select.  Capybara will not be throwing an exception for this behavior currently (just issuing a warning - which will also issue for poltergeist), so I would hope poltergeist throw since that would mean different drivers with different behaviors.   If you want your test to fail when trying to select a disabled element then you will need to assert that the value was or was not actually selected.

**Pull request merged**
