### PR TITLE
added session#last and specs, update history.md

### PR DESCRIPTION
**Pull request by Tmee**
I added Session#last which returns the last node found matching the given criteria.

### CODE REVIEW

**Comment by Tmee** [comment]
Hi @jnicklas, any thoughts on bringing this into the next release?

**Comment by twalpole** [comment]
@Tmee jnicklas doesn't really work on Capybara anymore - I'm the person doing most development nowadays.  My concern is whether `#last` justifies expanding the API .  Often while testing one wants to access the first element (or at least an element if any matches exist), I'm not sure how often last would be used, and it's already easy enough to just do `all(...).last`

**Comment by twalpole** [comment]
#first and #all  (and #last if added) also have the major downside of being non-reloadable elements, which can lead to all sorts of flaky test issues.

**Comment by Tmee** [comment]
ah, sorry about the @mention jnicklas.  Ok, I noticed I was typing `all(...).last` a bunch and thought it would be nice to have a `last(...)` similar to the awesome `first(...)` finder.  But no worries, thanks for getting back to me!

**Comment by twalpole** [comment]
If you don't mind explaining - what type of testing are you doing that you're calling `all(..).last` all the time?

**Comment by Tmee** [comment]
Just UI automation specs with selenium.  There have been a hand full of times, similar to the amount I use #first, that I've wanted to check the last element in table or in a list where I have to write out `all(...).last`.

**Comment by twalpole** [comment]
ok -- in most cases you're better off using last-child/last-of-type css selectors with `#find` if/when possible - People really tend to overuse #all/first and it causes a large number of the issues people have with Capybara being 'flaky'  due to it's lack of waiting behavior, and the result elements being non-reloadable

**Comment by Tmee** [comment]
ok, thanks for the info!

**Pull request closed without merging**
